INSERT INTO game_delivery_files (
  id, product_code, game_code, platform, version, object_key, filename, content_type,
  size, sha256, signature_status, scan_status, install_test_status, update_test_status,
  status, approved_by, approved_at, created_at, updated_at
) VALUES (
  'gs-game-001-win-1-0-2',
  'GS-GAME-001-WIN',
  'GS-GAME-001',
  'windows-x64',
  '1.0.2',
  'game-deliveries/gs-game-001/windows-x64/The-Wound-Remembers-Setup-1.0.2-8583038509.exe',
  'The-Wound-Remembers-Setup-1.0.2.exe',
  'application/vnd.microsoft.portable-executable',
  379498399,
  '85830385096300edc17fcd79a8210a212848f081e044160fe6e33cf31240d810',
  'unsigned_disclosed',
  'passed',
  'passed',
  'deferred_first_release',
  'approved',
  NULL,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
) ON CONFLICT (product_code) DO UPDATE SET
  game_code = excluded.game_code,
  platform = excluded.platform,
  version = excluded.version,
  object_key = excluded.object_key,
  filename = excluded.filename,
  content_type = excluded.content_type,
  size = excluded.size,
  sha256 = excluded.sha256,
  signature_status = excluded.signature_status,
  scan_status = excluded.scan_status,
  install_test_status = excluded.install_test_status,
  update_test_status = excluded.update_test_status,
  status = excluded.status,
  approved_by = NULL,
  approved_at = CURRENT_TIMESTAMP,
  updated_at = CURRENT_TIMESTAMP;
