export default {
  slug: "hogwarts-legacy", code: "LW-ATLAS-HWL-001", game: "Hogwarts Legacy",
  title: "Il taccuino dell’Antica Magia",
  subtitle: "Dalla prima lezione ai segreti del castello, costruendo un mago leggibile senza perdere la meraviglia.",
  description: "edizioni, accessibilità, casa, incantesimi, combattimento, talenti, equipaggiamento, pozioni, piante, esplorazione, enigmi, Stanza delle Necessità, creature, relazioni, volo e completamento",
  versionLabel: "Edizione completa · verifica 24 agosto 2026",
  vipFrom: "2026-09-21T00:00:00+02:00", publicAt: "2026-09-28T00:00:00+02:00",
  storeUrl: "https://www.hogwartslegacy.com/", storeLabel: "Apri il sito ufficiale di Hogwarts Legacy",
  palette: { dark: "#10142b", mid: "#3a204f", deep: "#08101d", accent: "#e7b85b" },
  chapters: [
    ["editions-accessibility","Edizioni e accessibilità","Preparare il viaggio prima dello Smistamento","Piattaforma, salvataggi, difficoltà, sottotitoli e opzioni di accessibilità definiscono il modo in cui leggerai combattimenti ed esplorazione.","Verifica edizione e contenuti installati|Regola luminosità, mira e sensibilità|Attiva sottotitoli e indicatori utili|Crea un salvataggio manuale iniziale|Prova la difficoltà per almeno due scontri","Conserva più salvataggi manuali|Riduci la difficoltà se impedisce di imparare|Distingui opzioni estetiche e aiuti di gioco","Non trovo un contenuto=>Controlla piattaforma, edizione e stato del download|I comandi risultano confusi=>Ripristina una configurazione semplice e cambia una voce alla volta"],
    ["house-character","Casa e personaggio","Scegliere un’identità che duri oltre il colore della divisa","Casa, aspetto e tono dei dialoghi definiscono l’interpretazione, ma non devono diventare una ricerca ansiosa della scelta perfetta.","Definisci il tono del personaggio|Ascolta la proposta del Cappello|Scegli la casa che vuoi abitare|Mantieni coerenti nome e aspetto|Salva prima di confermare","La casa cambia soprattutto atmosfera e spazi|Evita di consultare conseguenze narrative in anticipo|Scegli ciò che desideri vedere per molte ore","Temo di perdere contenuti=>Considera una seconda partita invece di annullare la prima scelta|Il personaggio non mi rappresenta=>Correggi gli elementi modificabili e conserva il ruolo scelto"],
    ["first-days","Prime lezioni","Imparare il castello senza inseguire ogni icona","Le prime ore introducono sistemi in sequenza: seguire le lezioni principali sblocca strumenti che rendono più chiara l’esplorazione successiva.","Completa le lezioni introduttive|Impara a usare Revelio con misura|Apri i punti di viaggio rapido incontrati|Prova ogni incantesimo appena appreso|Rientra spesso nel menu delle sfide","Segui una missione principale e una deviazione|Osserva porte, simboli e percorsi verticali|Non vendere subito ogni oggetto nuovo","Mi perdo nel castello=>Usa la mappa per piano e scegli un solo punto di arrivo|Ho troppe missioni=>Segna un obiettivo principale e ignora temporaneamente gli altri"],
    ["spells-sets","Incantesimi","Costruire set di magie facili da ricordare","Colori, tempi di recupero e funzioni dividono gli incantesimi in famiglie; un buon set assegna a ogni pulsante un lavoro riconoscibile.","Metti un attacco base in memoria muscolare|Associa controllo e danno nello stesso set|Crea un set per esplorazione|Crea un set per la Stanza delle Necessità|Prova le combinazioni su bersagli isolati","Usa la posizione prima del cooldown|Abbina incantesimi che sollevano e colpiscono|Mantieni sempre accessibile una risposta difensiva","Cambio set per errore=>Ordina i set per funzione e non per momento di sblocco|Un nemico resiste=>Leggi il colore dello scudo e usa la famiglia corretta"],
    ["combat-defense","Combattimento e difesa","Leggere il duello prima di lanciare la combo","Protego, schivata, controllo e priorità dei bersagli decidono lo scontro più del numero di incantesimi disponibili.","Osserva gli indicatori sopra il personaggio|Usa Protego quando l’attacco è parabile|Schiva gli attacchi non parabili|Rompi lo scudo corretto|Concentra il gruppo su un bersaglio per volta","Sposta la telecamera prima di attaccare|Usa oggetti e ambiente contro i gruppi|Conserva Magia Antica per le vere emergenze","Subisco colpi fuori campo=>Aumenta distanza e ruota la telecamera|Le combo si interrompono=>Riduci la sequenza e inserisci controllo o difesa"],
    ["talents-build","Talenti","Spendere punti su azioni già affidabili","I talenti migliorano strumenti esistenti: la build migliore nasce da ciò che usi davvero, non da un elenco copiato senza contesto.","Individua tre incantesimi ricorrenti|Scegli un nucleo tra controllo, danno e furtività|Compra un miglioramento difensivo|Prova il talento prima del successivo|Mantieni punti liberi finché hai dubbi","Potenzia prima il ciclo principale|Evita di distribuire punti in ogni ramo|Considera pozioni e piante parte della build","Ho speso male i punti=>Rafforza il nucleo restante invece di ricominciare subito|La build funziona solo contro un nemico=>Aggiungi una risposta universale di controllo o difesa"],
    ["gear-traits","Equipaggiamento e tratti","Separare potenza, aspetto e collezione","Livello, rarità, statistiche, tratti e trasmogrificazione risolvono bisogni diversi; non conservare ogni mantello soltanto per l’aspetto.","Confronta il valore offensivo o difensivo|Identifica i tratti utili alla build|Sblocca l’aspetto prima di vendere|Migliora soltanto pezzi destinati a durare|Libera gli slot prima di una missione lunga","L’aspetto resta disponibile dopo aver venduto|Apri le prove che ampliano l’inventario|Conserva materiali rari per miglioramenti reali","Inventario sempre pieno=>Vendi i doppioni e completa prove dedicate|Un pezzo più alto sembra peggiore=>Confronta statistiche, tratto e costo di miglioramento"],
    ["potions-plants","Pozioni e piante","Preparare strumenti che cambiano il ritmo dello scontro","Pozioni e piante non sono decorazioni: riducono pressione, creano finestre e permettono di affrontare gruppi senza dipendere soltanto dalle combo.","Coltiva una risorsa difensiva|Prepara una pozione offensiva|Assegna gli strumenti alla ruota rapida|Provali fuori dalle missioni difficili|Rifornisci prima di lasciare il castello","Usa una risorsa quando evita più danni del suo costo|Coltiva ciò che consumi regolarmente|Non accumulare strumenti senza provarli","Finisco le scorte=>Crea una routine tra coltivazione e missioni|Dimentico gli strumenti=>Inseriscili nel primo ciclo di ogni scontro impegnativo"],
    ["world-map","Esplorazione e mappa","Leggere Hogwarts, Hogsmeade e le Highlands come tre spazi diversi","Il castello è verticale, Hogsmeade è commerciale e le Highlands richiedono orientamento a distanza: una sola abitudine non basta per tutti.","Apri i punti di viaggio mentre attraversi una zona|Segna una deviazione per percorso|Usa Revelio dopo aver osservato|Controlla altezza e piano della destinazione|Rientra con inventario e scorte ordinati","Segui suoni e dettagli prima delle icone|Esplora per quartieri e non in modo casuale|Conserva alcune scoperte per il ritorno","L’indicatore sembra vicino ma non arrivo=>Controlla piano, scala o ingresso esterno|La mappa è piena=>Filtra mentalmente una categoria per sessione"],
    ["puzzles-secrets","Enigmi e segreti","Risolvere il linguaggio del castello senza aprire subito una soluzione","Simboli, luce, movimento e ordine costituiscono un vocabolario ricorrente. Prima di cercare la risposta, identifica quale elemento reagisce.","Osserva tutti gli oggetti interattivi|Prova Revelio una sola volta|Associa ogni simbolo a un’azione|Cambia posizione e prospettiva|Annota il tentativo che ha prodotto una reazione","Molti enigmi insegnano la regola vicino al primo esempio|La soluzione può richiedere un incantesimo non ancora appreso|Usa gli aiuti graduati prima della risposta completa","Nulla reagisce=>Potrebbe mancare un incantesimo o l’angolo corretto|Conosco la regola ma non l’ordine=>Ripristina la sequenza e osserva il feedback di ogni passaggio"],
    ["room-requirement","Stanza delle Necessità","Trasformare la stanza in un vero campo base","La stanza collega creazione, identificazione, miglioramenti, piante, pozioni e creature. Organizzala per ridurre i viaggi e rendere visibili le scorte.","Crea una zona per pozioni|Crea una zona per coltivazione|Raggruppa identificazione e miglioramento|Lascia corridoi leggibili|Salva dopo grandi modifiche","La funzione viene prima della decorazione|Aumenta capacità soltanto quando serve|Usa disposizioni coerenti tra stanze","Non trovo una postazione=>Raggruppa gli strumenti per ciclo di utilizzo|Produzione troppo lenta=>Controlla vasi, tavoli e ricette realmente necessari"],
    ["beasts-vivariums","Creature e vivarium","Curare le creature senza trasformarle in un inventario","Cattura, cura e allevamento devono sostenere la relazione e i materiali, senza riempire ogni spazio con esemplari raccolti senza progetto.","Prepara lo strumento di cattura|Riduci il pericolo nell’area|Avvicinati con controllo|Assegna la creatura al vivarium adatto|Crea una routine di cura e raccolta","Cibo e spazzola rendono leggibile il ciclo|Mantieni spazio per nuove specie|Decora senza bloccare i percorsi","La creatura fugge=>Usa controllo e avvicinati prima di iniziare|Il vivarium è caotico=>Riduci il numero e separa le specie per spazio"],
    ["companions-quests","Relazioni e missioni","Seguire le storie personali senza bruciare le conseguenze","Le missioni dei compagni hanno tono e soglie diverse. Leggi i dialoghi, conserva un salvataggio e apri gli spoiler solo quando la scelta è davvero bloccante.","Completa il dialogo opzionale|Leggi il diario prima di partire|Porta strumenti coerenti con la missione|Salva prima delle decisioni esplicite|Concludi il confronto dopo la missione","Non tutte le richieste vanno accettate subito|Distingui curiosità del giocatore e motivazione del personaggio|Usa dettagli spoiler richiudibili","Ho perso il filo narrativo=>Rileggi le ultime voci del diario|Temo una scelta irreversibile=>Crea un salvataggio nominabile prima del dialogo", "Spoiler protetti"],
    ["broom-travel","Scopa e movimento","Volare con controllo prima di inseguire il tempo migliore","Volo, gare e atterraggi richiedono una sensibilità diversa dal movimento a piedi. Prima costruisci precisione, poi velocità.","Prova decollo e atterraggio in spazio aperto|Regola la telecamera|Segui un percorso senza accelerazione continua|Impara a correggere altezza in anticipo|Affronta la gara dopo un giro di prova","Guarda due anelli avanti|Rilascia accelerazione nelle correzioni strette|Usa il volo per orientarti, non per saltare ogni scoperta","Perdo gli anelli=>Riduci velocità e anticipa la curva|Atterro lontano=>Allinea direzione e quota prima del comando"],
    ["challenges-collections","Sfide e collezioni","Completare senza trasformare il mondo in una lista","Le sfide premiano categorie di attività e spesso sbloccano capacità utili. Scegli una raccolta per sessione e lascia che il resto emerga durante il viaggio.","Controlla la ricompensa della categoria|Scegli una regione limitata|Segna ciò che richiede un ritorno|Completa la soglia utile|Riscatta manualmente le ricompense","Dai priorità agli ampliamenti funzionali|Non cercare l’ultimo oggetto senza verificare i filtri|Alterna raccolta e missioni","Il conteggio non avanza=>Controlla categoria, regione e ricompensa non riscattata|Manca un solo elemento=>Verifica interni, missioni e contenuti legati alla progressione"],
    ["completion-saves","Finale e seconda partita","Chiudere l’anno conservando ciò che rende unica la prima avventura","Il completamento può significare storia, sfide, collezioni o un nuovo personaggio. Definisci il tuo traguardo prima di inseguire il cento per cento.","Completa le missioni personali aperte|Conserva un salvataggio prima della soglia finale|Decidi quali collezioni ti interessano|Esporta mentalmente build e set preferiti|Crea un nuovo personaggio solo con un obiettivo diverso","Una seconda casa giustifica una nuova prospettiva|Conserva il salvataggio conclusivo separato|Non confondere trofeo e soddisfazione personale","Non so se ho finito=>Scrivi tre obiettivi personali e verifica se sono conclusi|Voglio ricominciare subito=>Cambia casa, stile o difficoltà per evitare di ripetere la stessa partita", "Spoiler protetti"]
  ],
  sections: [
    ["arrive","Entra nel castello","Edizione, identità e prime lezioni senza fretta.",["editions-accessibility","house-character","first-days"]],
    ["duel","Impara la magia","Incantesimi, difesa e talenti come sistema leggibile.",["spells-sets","combat-defense","talents-build"]],
    ["prepare","Prepara gli strumenti","Equipaggiamento, pozioni e piante al servizio della build.",["gear-traits","potions-plants"]],
    ["explore","Leggi il mondo","Mappa, segreti e volo senza inseguire ogni icona.",["world-map","puzzles-secrets","broom-travel"]],
    ["home","Costruisci il rifugio","Stanza delle Necessità e creature come campo base.",["room-requirement","beasts-vivariums"]],
    ["legacy","Proteggi la storia","Relazioni, sfide e completamento con spoiler separati.",["companions-quests","challenges-collections","completion-saves"]]
  ],
  sources: [
    ["Hogwarts Legacy · sito ufficiale","https://www.hogwartslegacy.com/"],
    ["Hogwarts Legacy · domande frequenti","https://www.hogwartslegacy.com/en-us/faq"],
    ["Hogwarts Legacy · accessibilità","https://www.hogwartslegacy.com/en-us/accessibility"],
    ["Portkey Games · Hogwarts Legacy","https://www.portkeygames.com/game/hogwarts-legacy/"],
    ["WB Games Support · Hogwarts Legacy","https://portkeygamessupport.wbgames.com/hc/en-us/categories/360004953714-Hogwarts-Legacy"]
  ]
};
