export default {
  slug: "the-sims-4", code: "LW-ATLAS-TS4-001", game: "The Sims 4",
  title: "Il diario di una vita possibile",
  subtitle: "Dalla prima famiglia a un quartiere vivo, con strumenti chiari per costruire, raccontare e proteggere i salvataggi.",
  description: "installazione, Crea un Sim, aspirazioni, Modalità Costruisci, bisogni, abilità, carriere, relazioni, denaro, mondi, calendario, pacchetti, Galleria, mod, salvataggi e aggiornamenti",
  versionLabel: "Gioco base e pacchetti · verifica 24 agosto 2026",
  vipFrom: "2026-10-05T00:00:00+02:00", publicAt: "2026-10-12T00:00:00+02:00",
  storeUrl: "https://www.ea.com/games/the-sims/the-sims-4", storeLabel: "Apri il sito ufficiale di The Sims 4",
  palette: { dark: "#123d54", mid: "#1b7f76", deep: "#092738", accent: "#a8ef5c" },
  living: { enabled: true, announcement: "Guida Viva: controlliamo aggiornamenti, pacchetti e compatibilità delle mod senza modificare automaticamente i contenuti.", scope: { expansion: "The Sims 4", contentUpdate: "Gioco base e pacchetti installati", season: "Aggiornamenti 2026" }, cadence: "monthly", lastCheckedAt: "2026-08-24", nextCheckAt: "2026-09-24T09:00:00+02:00", notificationTarget: "/notifiche", approvalRequired: true, monitoredSourceUrls: ["https://www.ea.com/games/the-sims/the-sims-4/news", "https://www.ea.com/games/the-sims/the-sims-4/download"] },
  chapters: [
    ["install-packs","Versione e pacchetti","Sapere quale gioco stai davvero avviando","Contenuti posseduti, installati e attivi non coincidono sempre: partire da un inventario evita ricerche su funzioni assenti.","Aggiorna gioco e launcher|Annota piattaforma e versione|Controlla i pacchetti installati|Avvia senza mod al primo test|Crea un salvataggio di prova","Aggiungi un pacchetto alla volta|Leggi i requisiti prima dell’acquisto|Distingui gioco base e contenuti opzionali","Un mondo non compare=>Verifica proprietà, download e filtri|Il gioco si chiude=>Prova riparazione e avvio senza contenuti personalizzati"],
    ["create-a-sim","Crea un Sim","Creare una persona prima di scegliere i vestiti","Età, tratti, aspirazione, voce, relazioni e stile formano un personaggio giocabile; definisci prima desideri e limiti.","Scegli una fase di vita|Definisci tre parole guida|Assegna tratti coerenti ma non identici|Scegli un’aspirazione iniziale|Crea relazioni della famiglia","Lascia spazio all’evoluzione|Prepara abiti per ogni categoria|Controlla pronomi, voce e camminata","Il Sim sembra generico=>Rafforza un desiderio e una contraddizione|La famiglia non è collegata=>Rivedi le relazioni prima di confermare"],
    ["aspirations-traits","Tratti e aspirazioni","Trasformare obiettivi astratti in una routine giocabile","Le aspirazioni orientano le tappe, i tratti influenzano reazioni e autonomia: usali come bussola, non come obbligo.","Leggi ogni tappa dell’aspirazione|Scegli un’attività quotidiana coerente|Individua un tratto che crea difficoltà|Controlla i punti soddisfazione|Cambia aspirazione quando cambia la storia","Alterna obiettivi brevi e lunghi|Non ottimizzare ogni emozione|Usa le ricompense con intenzione","L’aspirazione non avanza=>Controlla testo, luogo e Sim attivo|Il Sim ripete sempre la stessa azione=>Riduci autonomia mirata e offri alternative"],
    ["build-mode","Modalità Costruisci","Progettare una casa leggibile prima di decorarla","Percorsi, dimensioni, luce e budget determinano se la casa funziona; la decorazione arriva dopo una pianta attraversabile.","Traccia stanze e ingressi|Verifica spazio davanti agli oggetti|Posa luci provvisorie|Arreda bisogni essenziali|Prova la casa in Modalità Vivi","Costruisci dal percorso quotidiano|Usa griglia e filtri|Conserva una copia prima delle grandi modifiche","Un oggetto non è raggiungibile=>Libera le caselle e controlla porte|Il tetto attraversa la stanza=>Separa falde e verifica ogni piano"],
    ["live-mode-needs","Bisogni e autonomia","Leggere una giornata senza inseguire ogni barra","I bisogni segnalano priorità, ma tempo, distanza ed emozioni spiegano perché un comando riesce o viene annullato.","Metti in pausa e leggi le barre|Ordina prima il bisogno critico|Riduci tragitti inutili|Accoda poche azioni compatibili|Controlla il risultato prima di accelerare","Mantieni bagno e cucina accessibili|Lascia margine prima di lavoro o scuola|Osserva l’autonomia prima di correggerla","Le azioni spariscono=>Controlla percorso, oggetto e stato emotivo|Tutti sono esausti=>Semplifica la routine e distribuisci gli orari"],
    ["skills","Abilità","Imparare con un progetto invece che con una barra","Un’abilità cresce meglio quando serve a un obiettivo concreto: un piatto, un quadro, una riparazione o una relazione.","Scegli una competenza principale|Compra lo strumento minimo|Inserisci sessioni brevi|Sfrutta stati emotivi utili|Vendi o usa ciò che produci","Alterna studio e pratica|Evita di allenare tutti allo stesso modo|Trasforma i risultati in arredamento o reddito","La crescita è lenta=>Controlla umore, qualità dello strumento e continuità|Il Sim abbandona l’attività=>Soddisfa prima i bisogni urgenti"],
    ["careers","Carriere e scuola","Far convivere orari, prestazioni e vita personale","Promozioni e voti richiedono compiti, abilità e buon umore; pianifica il giorno prima senza ridurre la famiglia a una catena produttiva.","Leggi orario e requisiti|Completa il compito giornaliero|Prepara bisogni la sera|Sviluppa l’abilità richiesta|Conserva tempo libero dopo il turno","Usa ferie prima del collasso|Scegli una carriera coerente con la storia|Non sacrificare ogni relazione alla prestazione","La prestazione non sale=>Controlla atteggiamento e compito|Il Sim perde il lavoro=>Verifica orari, ritardi e assenze"],
    ["relationships","Relazioni e famiglia","Costruire legami attraverso contesto e continuità","Barre sociali, sentimenti, compatibilità e ricordi possono raccontare rapporti diversi; non forzare una singola interazione ripetuta.","Presentati nel tono giusto|Alterna conversazione e attività|Leggi reazioni e stati emotivi|Crea occasioni ricorrenti|Lascia evolvere conflitti e riconciliazioni","I piccoli contatti mantengono i legami|Rispetta orientamenti e preferenze|Salva prima dei grandi cambi familiari","Una relazione scende rapidamente=>Controlla interazioni fallite e sentimenti|L’evento romantico non parte=>Verifica età, preferenze e contesto"],
    ["money-household","Denaro domestico","Creare sicurezza senza eliminare ogni imprevisto","Bollette, pasti, riparazioni e ampliamenti competono per lo stesso budget; separa spese necessarie, crescita e desideri.","Calcola le bollette previste|Mantieni una riserva|Compra strumenti che producono valore|Vendi oggetti inutilizzati|Amplia una stanza alla volta","La qualità non serve ovunque|Ripara se il rischio è gestibile|Usa il lotto come investimento narrativo","Non riesco a pagare=>Vendi eccedenze e riduci costi ricorrenti|La casa è piena ma povera=>Valuta inventari e oggetti decorativi costosi"],
    ["worlds-travel","Mondi e viaggi","Usare il quartiere come parte della storia","Lotti comunitari, vicini, servizi e mondi installati offrono risorse diverse; viaggiare con uno scopo riduce caricamenti e dispersione.","Esplora il quartiere a piedi|Segna servizi utili|Visita un lotto per obiettivo|Invita il gruppo corretto|Rientra prima dei bisogni critici","Salva prima dei grandi spostamenti|Usa parchi e biblioteche come risorse|Controlla regole del lotto","Un lotto non appare=>Verifica pacchetto e gestione mondi|Il gruppo si separa=>Seleziona i partecipanti prima del viaggio"],
    ["calendar-events","Calendario ed eventi","Dare ritmo alla famiglia senza riempire ogni giorno","Festività, compleanni ed eventi sociali funzionano meglio quando preparazione, ospiti e obiettivi rispettano la capacità reale della casa.","Controlla la settimana in anticipo|Prepara spazio e oggetti|Invita pochi ospiti pertinenti|Completa prima gli obiettivi semplici|Lascia tempo per chiudere l’evento","Crea tradizioni sostenibili|Non sovrapporre lavoro ed evento|Usa eventi senza medaglia quando vuoi libertà","La festa fallisce=>Riduci obiettivi e migliora accessibilità del lotto|Un compleanno passa inosservato=>Controlla calendario e torta prima dell’orario"],
    ["packs-scope","Pacchetti e sistemi","Aggiungere contenuti senza perdere il centro della partita","Espansioni, Game Pack, Stuff Pack e kit introducono mondi, sistemi e oggetti diversi; scegli ciò che sostiene la storia corrente.","Definisci la funzione desiderata|Leggi cosa include davvero il pacchetto|Controlla compatibilità e spazio|Installa prima su un salvataggio copia|Integra un sistema alla volta","Non comprare solo per un singolo oggetto|Disattiva ciò che non vuoi usare|Mantieni una nota dei pacchetti attivi","Una guida cita un sistema assente=>Controlla il pacchetto richiesto|Dopo l’installazione tutto cambia=>Prova un salvataggio nuovo e verifica conflitti"],
    ["gallery","Galleria e Biblioteca","Condividere creazioni senza perdere dipendenze e attribuzione","La Galleria rende immediato importare lotti e famiglie, ma filtri, contenuti personalizzati e pacchetti mancanti cambiano il risultato.","Controlla connessione e account|Filtra per tipo e pacchetti posseduti|Leggi descrizione e crediti|Salva prima nella Biblioteca|Posiziona su un lotto compatibile","Verifica sostituzioni degli oggetti|Attribuisci sempre l’autore|Conserva una copia locale delle tue creazioni","Il lotto è incompleto=>Controlla pacchetti e contenuti personalizzati|Non trovo la creazione=>Rivedi filtri e voce Contenuti personalizzati"],
    ["mods-custom-content","Mod e contenuti personalizzati","Personalizzare senza affidare il salvataggio al caso","Mod e CC sono esterni al gioco: aggiornamenti, dipendenze e ordine richiedono una cartella leggibile e un test controllato.","Fai backup dei salvataggi|Aggiorna una mod dalla fonte originale|Leggi dipendenze e versione|Prova in piccoli gruppi|Rimuovi la cache quando indicato","Separa mod script e cosmetiche|Conserva un elenco con versioni|Dopo una patch avvia prima senza mod","Il gioco non parte=>Sposta temporaneamente la cartella Mods e testa|Interfaccia deformata=>Aggiorna prima le mod che cambiano UI"],
    ["saves-recovery","Salvataggi e diagnosi","Proteggere anni virtuali con copie comprensibili","Salva con nome, backup e versioni separate prima di patch, mod o ristrutturazioni; ripara una variabile per volta.","Usa Salva con nome periodicamente|Copia la cartella dei salvataggi|Conserva tre generazioni|Prova il recupero su una copia|Annota l’ultima modifica stabile","Non sincronizzare alla cieca file corrotti|Distingui lotto, famiglia e salvataggio|Verifica lo spazio libero","Un salvataggio non compare=>Controlla cartella, profilo e file recuperabili|Il lotto resta bloccato=>Prova un’altra famiglia e ripara il gioco"],
    ["living-updates","Guida Viva","Aggiornare il gioco senza riscrivere la famiglia","The Sims 4 continua a ricevere patch e contenuti: la guida monitora fonti ufficiali, segnala cambiamenti e attende approvazione editoriale.","Leggi note ufficiali|Fai backup prima della patch|Controlla mod e CC|Prova una copia del salvataggio|Approva soltanto correzioni verificate","Non aggiornare una guida da indiscrezioni|Separa novità gratuite e pacchetti|Registra data e piattaforme interessate","Una meccanica è cambiata=>Confronta note ufficiali e prova pulita|Una mod è incompatibile=>Attendi l’autore o rimuovila dalla copia di test"]
  ],
  sections: [
    ["start","Crea la famiglia","Versione, identità e obiettivi iniziali.",["install-packs","create-a-sim","aspirations-traits"]],
    ["home","Costruisci la casa","Spazi, bisogni e denaro domestico.",["build-mode","live-mode-needs","money-household"]],
    ["grow","Fai crescere le vite","Abilità, carriere e relazioni.",["skills","careers","relationships"]],
    ["world","Abita il quartiere","Mondi, calendario e contenuti installati.",["worlds-travel","calendar-events","packs-scope"]],
    ["share","Condividi con cura","Galleria, mod e salvataggi protetti.",["gallery","mods-custom-content","saves-recovery"]],
    ["live","Segui gli aggiornamenti","Controllo mensile della Guida Viva.",["living-updates"]]
  ],
  sources: [["The Sims 4 · sito ufficiale","https://www.ea.com/games/the-sims/the-sims-4"],["The Sims 4 · notizie","https://www.ea.com/games/the-sims/the-sims-4/news"],["The Sims 4 · download","https://www.ea.com/games/the-sims/the-sims-4/download"],["EA Help · The Sims 4","https://help.ea.com/en/games/the-sims/the-sims-4/"]]
};
