"use client";

import { useCallback, useEffect, useState } from "react";
type Ticket = { id: string; referenceCode: string; customerEmail: string; customerName: string | null; category: string; subject: string; description: string; productCode: string | null; status: string; priority: string; adminNotes: string; createdAt: string; updatedAt: string };
const statusOptions = ["open", "reviewing", "waiting_user", "resolved", "closed"]; const priorityOptions = ["low", "normal", "high", "critical"];
export function SupportAdminDashboard() {
  const [tickets, setTickets] = useState<Ticket[]>([]); const [filter, setFilter] = useState("active"); const [message, setMessage] = useState("Caricamento richieste…"); const [busyId, setBusyId] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/admin/support-tickets", { headers: { accept: "application/json" }, cache: "no-store" }); const body = await response.json() as { tickets?: Ticket[]; error?: string }; if (!response.ok) throw new Error(body.error || "Richieste non disponibili."); setTickets(body.tickets ?? []); setMessage(""); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((error: Error) => setMessage(error.message)); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function save(ticket: Ticket, next: Partial<Ticket>) { setBusyId(ticket.id); setMessage("Salvataggio…"); try { const response = await fetch("/api/admin/support-tickets", { method: "PATCH", headers: { "Content-Type": "application/json", accept: "application/json" }, body: JSON.stringify({ id: ticket.id, status: next.status ?? ticket.status, priority: next.priority ?? ticket.priority, adminNotes: next.adminNotes ?? ticket.adminNotes }) }); const body = await response.json() as { error?: string }; if (!response.ok) throw new Error(body.error || "Aggiornamento non riuscito."); await load(); setMessage("Richiesta aggiornata."); } catch (error) { setMessage(error instanceof Error ? error.message : "Aggiornamento non riuscito."); } finally { setBusyId(""); } }
  const visible = tickets.filter((ticket) => filter === "all" || (filter === "active" ? !["resolved", "closed"].includes(ticket.status) : ticket.status === filter));
  return <section className="support-admin-dashboard"><header><div><p className="eyebrow">Coda operativa</p><h2>Assistenza LoreWise.</h2><p>Ogni pratica conserva utente, area, riferimento, priorità e risposta visibile nell’account.</p></div><strong>{visible.length}<span>visualizzate</span></strong></header><div className="support-admin-toolbar"><label>Mostra<select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="active">Solo aperte</option><option value="all">Tutte</option>{statusOptions.map((value) => <option value={value} key={value}>{value}</option>)}</select></label><button type="button" onClick={() => void load()} disabled={Boolean(busyId)}>Aggiorna</button></div>{message ? <p role="status">{message}</p> : null}<div className="support-admin-list">{visible.map((ticket) => <TicketEditor key={ticket.id} ticket={ticket} busy={busyId === ticket.id} onSave={save} />)}{!visible.length ? <p>Nessuna richiesta corrisponde al filtro.</p> : null}</div></section>;
}
function TicketEditor({ ticket, busy, onSave }: { ticket: Ticket; busy: boolean; onSave: (ticket: Ticket, next: Partial<Ticket>) => Promise<void> }) { const [status, setStatus] = useState(ticket.status); const [priority, setPriority] = useState(ticket.priority); const [notes, setNotes] = useState(ticket.adminNotes); return <article className={`support-admin-ticket priority-${priority}`}><header><div><small>{ticket.referenceCode} · {ticket.category}</small><h3>{ticket.subject}</h3><a href={`mailto:${ticket.customerEmail}`}>{ticket.customerName || ticket.customerEmail}</a></div><code>{ticket.productCode || "Nessun codice"}</code></header><p>{ticket.description}</p><div className="support-admin-editor"><label>Stato<select value={status} onChange={(event) => setStatus(event.target.value)}>{statusOptions.map((value) => <option value={value} key={value}>{value}</option>)}</select></label><label>Priorità<select value={priority} onChange={(event) => setPriority(event.target.value)}>{priorityOptions.map((value) => <option value={value} key={value}>{value}</option>)}</select></label><label>Risposta visibile all’utente<textarea value={notes} onChange={(event) => setNotes(event.target.value)} rows={5} maxLength={4000} /></label><button type="button" disabled={busy} onClick={() => void onSave(ticket, { status, priority, adminNotes: notes })}>{busy ? "Salvataggio…" : "Salva e aggiorna"}</button></div></article>; }
