"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";

type Ticket = { referenceCode: string; category: string; subject: string; description: string; productCode: string | null; status: string; priority: string; adminNotes: string | null; createdAt: string; updatedAt: string };
const categories = [["game", "Gioco o applicazione"], ["download", "Download o installazione"], ["account", "LoreWise ID"], ["commission", "Commissione"], ["subscription", "Universe Pass"], ["privacy", "Privacy e dati"], ["other", "Altro"]];
const statuses: Record<string, string> = { open: "Ricevuta", reviewing: "In lavorazione", waiting_user: "In attesa di risposta", resolved: "Risolta", closed: "Chiusa" };

export function SupportTicketCenter() {
  const [tickets, setTickets] = useState<Ticket[]>([]); const [authenticated, setAuthenticated] = useState<boolean | null>(null);
  const [category, setCategory] = useState("game"); const [subject, setSubject] = useState(""); const [description, setDescription] = useState(""); const [productCode, setProductCode] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const load = useCallback(async () => { const response = await fetch("/api/support-tickets", { headers: { accept: "application/json" }, cache: "no-store" }); if (response.status === 401) { setAuthenticated(false); return; } const body = await response.json() as { tickets?: Ticket[]; error?: string }; if (!response.ok) throw new Error(body.error || "Archivio assistenza non disponibile."); setAuthenticated(true); setTickets(body.tickets ?? []); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((error: Error) => setMessage(error.message)); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setMessage("Registrazione della richiesta…"); try { const response = await fetch("/api/support-tickets", { method: "POST", headers: { "Content-Type": "application/json", accept: "application/json" }, body: JSON.stringify({ category, subject, description, productCode }) }); const body = await response.json() as { success?: boolean; referenceCode?: string; message?: string; error?: string }; if (!response.ok || !body.success) throw new Error(body.error || "Richiesta non registrata."); setMessage(`${body.message} Riferimento: ${body.referenceCode}`); setSubject(""); setDescription(""); setProductCode(""); await load(); } catch (error) { setMessage(error instanceof Error ? error.message : "Richiesta non registrata."); } finally { setBusy(false); } }
  if (authenticated === false) return <section className="support-ticket-center support-ticket-signed-out" id="ticket"><p className="eyebrow">Centro assistenza personale</p><h2>Una richiesta, un riferimento verificabile.</h2><p>Accedi per collegare automaticamente la segnalazione al tuo LoreWise ID e ritrovarla nello storico.</p><Link href="/account">Accedi al LoreWise ID →</Link></section>;
  return <section className="support-ticket-center" id="ticket" aria-labelledby="support-ticket-title"><header><div><p className="eyebrow">Centro assistenza personale</p><h2 id="support-ticket-title">Apri e segui una richiesta.</h2><p>Non inserire password, codici di pagamento completi o altri segreti. Il Centro Admin riceverà subito una notifica collegata al riferimento.</p></div><strong>{tickets.filter((ticket) => !["resolved", "closed"].includes(ticket.status)).length}<span>aperte</span></strong></header><div className="support-ticket-layout"><form onSubmit={submit}><label>Area<select value={category} onChange={(event) => setCategory(event.target.value)}>{categories.map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><label>Oggetto<input value={subject} onChange={(event) => setSubject(event.target.value)} minLength={5} maxLength={120} required placeholder="Descrivi il problema in una riga" /></label><label>Gioco, ordine o codice collegato<input value={productCode} onChange={(event) => setProductCode(event.target.value)} maxLength={80} placeholder="Facoltativo: GS-GAME-001, LW-…" /></label><label>Descrizione<textarea value={description} onChange={(event) => setDescription(event.target.value)} minLength={30} maxLength={4000} required rows={7} placeholder="Cosa è successo, su quale dispositivo e quali passaggi hai già provato?" /></label><button type="submit" disabled={busy}>{busy ? "Invio…" : "Invia al Centro Admin"}</button>{message ? <p role="status">{message}</p> : null}</form><div className="support-ticket-history"><h3>Le tue richieste</h3>{tickets.length ? <ol>{tickets.map((ticket) => <li key={ticket.referenceCode}><header><div><small>{ticket.referenceCode} · {ticket.category}</small><strong>{ticket.subject}</strong></div><span>{statuses[ticket.status] ?? ticket.status}</span></header><p>{ticket.description}</p>{ticket.productCode ? <code>{ticket.productCode}</code> : null}{ticket.adminNotes ? <blockquote><strong>Risposta GiWise Studio</strong>{ticket.adminNotes}</blockquote> : null}</li>)}</ol> : <p>Nessuna richiesta registrata. Quando ne aprirai una, stato e risposta resteranno visibili qui.</p>}</div></div></section>;
}
