import type { FamiliarItemKey } from "./nexusFamiliar.ts";

export type FamiliarMissionActivity = "artwork_visit" | "guide_visit" | "chronicle_visit" | "project_visit" | "artwork_like" | "meaningful_comment" | "comment_like" | "familiar_care" | "familiar_battle" | "familiar_expedition" | "familiar_tower_floor" | "daily_return";
export type FamiliarMissionGroup = "explore" | "connect" | "care" | "combat" | "expedition";
export type FamiliarMissionDifficulty = "facile" | "normale" | "difficile";
export type FamiliarMissionDefinition = { id: string; group: FamiliarMissionGroup; difficulty: FamiliarMissionDifficulty; activity: FamiliarMissionActivity; title: string; description: string; target: number; reward: { item: FamiliarItemKey; quantity: number }; href: string };

const MISSIONS: FamiliarMissionDefinition[] = [
  { id: "explore-art-2", group: "explore", difficulty: "facile", activity: "artwork_visit", title: "Passeggiata in galleria", description: "Apri e osserva 2 opere diverse.", target: 2, reward: { item: "toy", quantity: 1 }, href: "/arte" },
  { id: "explore-art-3", group: "explore", difficulty: "normale", activity: "artwork_visit", title: "Occhio del curatore", description: "Scopri 3 opere diverse dell’archivio.", target: 3, reward: { item: "soap", quantity: 2 }, href: "/arte" },
  { id: "explore-guide-1", group: "explore", difficulty: "facile", activity: "guide_visit", title: "Una nuova strada", description: "Consulta una guida di gioco.", target: 1, reward: { item: "food", quantity: 2 }, href: "/giochi/guide" },
  { id: "explore-guide-2", group: "explore", difficulty: "normale", activity: "guide_visit", title: "Rotte parallele", description: "Consulta 2 guide diverse.", target: 2, reward: { item: "toy", quantity: 2 }, href: "/giochi/guide" },
  { id: "explore-chronicle-1", group: "explore", difficulty: "facile", activity: "chronicle_visit", title: "Segnale dal Nexus", description: "Leggi una Cronaca del Nexus.", target: 1, reward: { item: "food", quantity: 2 }, href: "/cronache-del-nexus" },
  { id: "explore-project-2", group: "explore", difficulty: "normale", activity: "project_visit", title: "Dietro le quinte", description: "Esplora 2 progetti diversi.", target: 2, reward: { item: "soap", quantity: 2 }, href: "/dove-nascono-i-mondi" },
  { id: "connect-like-1", group: "connect", difficulty: "facile", activity: "artwork_like", title: "Un segno d’apprezzamento", description: "Metti Mi piace a un’opera.", target: 1, reward: { item: "food", quantity: 2 }, href: "/arte" },
  { id: "connect-like-2", group: "connect", difficulty: "normale", activity: "artwork_like", title: "Due scintille", description: "Metti Mi piace a 2 opere diverse.", target: 2, reward: { item: "food", quantity: 3 }, href: "/arte" },
  { id: "connect-like-3", group: "connect", difficulty: "difficile", activity: "artwork_like", title: "Traccia nella galleria", description: "Metti Mi piace a 3 opere diverse.", target: 3, reward: { item: "toy", quantity: 3 }, href: "/arte" },
  { id: "connect-comment-1", group: "connect", difficulty: "normale", activity: "meaningful_comment", title: "Lascia una riflessione", description: "Scrivi un commento pertinente di almeno 40 caratteri e 6 parole.", target: 1, reward: { item: "medicine", quantity: 1 }, href: "/arte" },
  { id: "connect-comment-2", group: "connect", difficulty: "difficile", activity: "meaningful_comment", title: "Dialogo con le opere", description: "Scrivi 2 commenti pertinenti su opere diverse.", target: 2, reward: { item: "medicine", quantity: 2 }, href: "/arte" },
  { id: "connect-community-2", group: "connect", difficulty: "normale", activity: "comment_like", title: "Voci da sostenere", description: "Apprezza 2 commenti di altri membri.", target: 2, reward: { item: "soap", quantity: 2 }, href: "/arte" },
  { id: "care-one", group: "care", difficulty: "facile", activity: "familiar_care", title: "Un gesto di cura", description: "Compi un’azione di cura nella Casa.", target: 1, reward: { item: "food", quantity: 2 }, href: "/famiglio" },
  { id: "care-two", group: "care", difficulty: "normale", activity: "familiar_care", title: "Rituale quotidiano", description: "Compi 2 azioni di cura diverse.", target: 2, reward: { item: "toy", quantity: 1 }, href: "/famiglio" },
  { id: "care-three", group: "care", difficulty: "difficile", activity: "familiar_care", title: "Casa in armonia", description: "Compi 3 azioni di cura diverse.", target: 3, reward: { item: "medicine", quantity: 2 }, href: "/famiglio" },
  { id: "return-today", group: "care", difficulty: "facile", activity: "daily_return", title: "Il Famiglio ti aspettava", description: "Rientra nella Casa oggi.", target: 1, reward: { item: "food", quantity: 1 }, href: "/famiglio" },
  { id: "battle-two", group: "combat", difficulty: "normale", activity: "familiar_battle", title: "Due duelli del Nexus", description: "Porta a termine 2 lotte, anche nella Torre.", target: 2, reward: { item: "medicine", quantity: 2 }, href: "/famiglio?sezione=lotta" },
  { id: "battle-four", group: "combat", difficulty: "difficile", activity: "familiar_battle", title: "Veterano dell’Arena", description: "Porta a termine 4 lotte distinte.", target: 4, reward: { item: "medicine", quantity: 3 }, href: "/famiglio?sezione=lotta" },
  { id: "expedition-two", group: "expedition", difficulty: "normale", activity: "familiar_expedition", title: "Due sentieri", description: "Completa e riscuoti 2 spedizioni.", target: 2, reward: { item: "food", quantity: 4 }, href: "/famiglio?sezione=spedizioni" },
  { id: "expedition-three", group: "expedition", difficulty: "difficile", activity: "familiar_expedition", title: "Cartografo del Nexus", description: "Completa e riscuoti 3 spedizioni.", target: 3, reward: { item: "toy", quantity: 3 }, href: "/famiglio?sezione=spedizioni" },
  { id: "tower-floor-five", group: "combat", difficulty: "difficile", activity: "familiar_tower_floor", title: "Ascesa alla Torre", description: "Supera i primi 5 piani della Torre in una scalata.", target: 5, reward: { item: "medicine", quantity: 4 }, href: "/famiglio?sezione=lotta" },
];

export const FAMILIAR_MISSION_COUNT = 3;
export const MEANINGFUL_COMMENT_MIN_CHARACTERS = 40;
export const MEANINGFUL_COMMENT_MIN_WORDS = 6;
export function romeDateKey(now = new Date()) { const parts = new Intl.DateTimeFormat("en-CA", { timeZone: "Europe/Rome", year: "numeric", month: "2-digit", day: "2-digit" }).formatToParts(now); const value = Object.fromEntries(parts.map((part) => [part.type, part.value])); return `${value.year}-${value.month}-${value.day}`; }
export function previousRomeDateKey(date: string) { const [year, month, day] = date.split("-").map(Number); return new Date(Date.UTC(year, month - 1, day - 1, 12)).toISOString().slice(0, 10); }
function hashSeed(value: string) { let hash = 2166136261; for (let index = 0; index < value.length; index += 1) { hash ^= value.charCodeAt(index); hash = Math.imul(hash, 16777619); } return hash >>> 0; }
function pickForDifficulty(difficulty: FamiliarMissionDifficulty, seed: string, excluded: ReadonlySet<string>) { const pool = MISSIONS.filter((mission) => mission.difficulty === difficulty); const start = hashSeed(`${seed}:${difficulty}`) % pool.length; for (let offset = 0; offset < pool.length; offset += 1) { const candidate = pool[(start + offset) % pool.length]; if (!excluded.has(candidate.id)) return candidate; } return pool[start]; }
export function dailyFamiliarMissions(userId: string, date = romeDateKey(), previousMissionIds: string[] = []) { const excluded = new Set(previousMissionIds); return (["facile", "normale", "difficile"] as FamiliarMissionDifficulty[]).map((difficulty) => pickForDifficulty(difficulty, `${userId}:${date}`, excluded)); }
export function dailyFamiliarMissionsForCount(userId: string, date = romeDateKey(), previousMissionIds: string[] = [], count = FAMILIAR_MISSION_COUNT) { const core = dailyFamiliarMissions(userId, date, previousMissionIds); if (count <= core.length) return core.slice(0, count); const excluded = new Set([...previousMissionIds, ...core.map((mission) => mission.id)]); const remaining = MISSIONS.filter((mission) => !excluded.has(mission.id)); const selected = [...core]; for (let offset = 0; selected.length < count && remaining.length > 0; offset += 1) { const index = hashSeed(`${userId}:${date}:bonus:${offset}`) % remaining.length; selected.push(remaining.splice(index, 1)[0]); } return selected; }
export function familiarMissionById(id: string) { return MISSIONS.find((mission) => mission.id === id) ?? null; }
export function meaningfulMissionComment(text: string) { const normalized = text.normalize("NFKC").trim().replace(/\s+/g, " "); if (normalized.length < MEANINGFUL_COMMENT_MIN_CHARACTERS || /^(.)\1{7,}$/u.test(normalized.replace(/\s/g, ""))) return false; const words = normalized.toLocaleLowerCase("it").match(/[\p{L}\p{N}][\p{L}\p{N}'’-]*/gu) ?? []; return words.length >= MEANINGFUL_COMMENT_MIN_WORDS && new Set(words.filter((word) => word.length >= 3)).size >= 4; }
export function familiarVisitActivity(pathname: string): { activity: FamiliarMissionActivity; sourceKey: string } | null { const parsed = new URL(pathname, "https://lorewisenexus.local"); const path = parsed.pathname.replace(/\/+$/, "") || "/"; if (/^\/arte\/[^/]+$/i.test(path)) return { activity: "artwork_visit", sourceKey: path.toLocaleLowerCase("it") }; if (path === "/giochi/guide") { const game = parsed.searchParams.get("gioco")?.trim().toLocaleLowerCase("it") || "indice"; return { activity: "guide_visit", sourceKey: `${path}?gioco=${encodeURIComponent(game)}` }; } if (path === "/cronache-del-nexus" || /^\/cronache-del-nexus\/[^/]+$/i.test(path)) return { activity: "chronicle_visit", sourceKey: path.toLocaleLowerCase("it") }; if (/^\/dove-nascono-i-mondi\/(?:giochi\/)?[^/]+$/i.test(path)) return { activity: "project_visit", sourceKey: path.toLocaleLowerCase("it") }; return null; }
